name: FTP Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    env:
      password: ${{secrets.VITE_DB_PASSWORD}}
      username: ${{secrets.VITE_SOME_KEY}}
      email: ${{secrets.VITE_NEWKEY2}}

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./themes/our-awesome-theme

    steps:
      - name: Obtner ultimo codigo
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: composer install --prefer-dist --no-progress --no-suggest
        
      - name: Instalar npm
        run: npm install
        
      - name: Compilar proyecto
        run: npm run build
        
      - name: Sincronizar proyecto
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}

      - name: "Mostrando variables de entorno"
        run: |
          echo "Estos es el valor de usurname: ${{env.username}}"
          echo "Estos es el valor de password: ${{env.password}}"
          echo "Estos es el valor de email: ${{env.email}}"
