name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:

    env:
      password:
      username: ${{secrets.}}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Mostrar mensaje"
        run: echo "Hola mundo"

      - name: "Mostrando variables de entorno"
